WebApplication.Web/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication.Web.DAL;
using WebApplication.Web.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using WebApplication.Web.Extensions;
using WebApplication.Web.Models.Account;
using WebApplication.Web.Models.Authentication;
using WebApplication.Web.Providers.Auth;

namespace WebApplication.Web.Controllers
{
    public class AdministratorController : Controller
    {

        private const string USERNAMEKEY = "Auth_Username";
        UserSqlDAL userDAL = new UserSqlDAL(@"Data Source=.\SQLEXPRESS;Initial Catalog=WorkoutDB;Integrated Security=True");
        public IActionResult Index()
        {
            string currentUserName = HttpContext.Session.Get<string>(USERNAMEKEY);
            User currentUser = userDAL.GetUser(currentUserName);
            if (currentUser.Role != "admin")
            {
                return RedirectToAction("NotAuthorized");
            }
            else
            {
                return View();
            }
        }

        public IActionResult AddEmployee()
        {

            return View();
        }

        public IActionResult NotAuthorized()
        {
            return View();
        }

        [HttpPost]
        public ActionResult<dynamic> Register(RegisterViewModel model)
        {
            AuthenticationController myAuthentication = new AuthenticationController(userDAL);

            NewUserModel newUser = new NewUserModel()
            {
                Username = model.Email,
                Password = model.Password
            };

            var result = myAuthentication.EmployeeRegister(newUser);
            Message message = new Message();
            if (result.Result.GetType() == typeof(Microsoft.AspNetCore.Mvc.OkResult))
            {

                message.MyMessage = $"Congratulations! {newUser.Username} has been registered";
            }
            else
            {
                message.MyMessage = "There was an error in registering you.";
            }

            return RedirectToAction("Index", message);
        }
    }
}

WebApplication.Web/Views/Administrator/AddEmployee.cshtml
<link href="~/css/workout.css" rel="stylesheet" />
@using WebApplication.Web.Models.Account;
@model RegisterViewModel

@{
    ViewData["Title"] = "AddEmployee";
}

<h2>Register New Employee</h2>

<form asp-controller="Administrator" asp-action="register" method="post">
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" placeholder="Email" />
        <span asp-validation-for="Email"></span>
    </div>
    <div class="form-group">
        <label asp-for="Password"></label>
        <input type="password" asp-for="Password" />
        <span asp-validation-for="Password"></span>
    </div>
    <div class="form-group">
        <label asp-for="ConfirmPassword"></label>
        <input type="password" asp-for="ConfirmPassword" />
        <span asp-validation-for="ConfirmPassword"></span>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>

WebApplication.Web/Views/Administrator/Index.cshtml
<link href="~/css/workout.css" rel="stylesheet" />
@{
    ViewData["Title"] = "Index";
}

<div style="text-align:center">
    <h2>Administrator Page</h2>

    <a asp-controller="Administrator" asp-action="AddEmployee">Register New Employee</a>
</div>

WebApplication.Web/Views/Administrator/NotAuthorized.cshtml
<link href="~/css/workout.css" rel="stylesheet" />
@{
    ViewData["Title"] = "NotAuthorized";
}

<h2>Unauthorized Error</h2>

<p>Only system administrators are permitted to perform actions on this page. Click any other tab in the navigation bar (located at the top of the page) to exit.</p>